services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    command: ./scripts/service_start.sh web
    depends_on:
      - postgres

volumes:
  db_data:
