services:
  web:
    image: python:3.11
    command: bash -c "chmod +x compose_start.sh && ./compose_start.sh"
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data:
