version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "chmod +x ./scripts/*.sh && ./scripts/compose_start.sh"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: celery -A palpiteiros worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq

  beat:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: celery -A palpiteiros beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq

  flower:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: celery flower
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - web
      - worker

volumes:
  db_data:
