version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # rabbitmq:
  #   image: rabbitmq:3-alpine
  #   ports:
  #     - 5672:5672

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "chmod +x ./scripts/*.sh && ./scripts/service_start.sh web"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      # - rabbitmq

  worker_beat:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bash -c "chmod +x ./scripts/*.sh && ./scripts/service_start.sh worker_beat"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      # - rabbitmq

  flower:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: celery flower
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - redis
      # - rabbitmq
      - web
      - worker_beat

volumes:
  db_data:
