[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 120
max-complexity = 7
exclude = ["migrations", "venv"]
ignore = ["E501", "W503"]

[tool.pytest.ini_options]
python_files = ["test_*.py", "tests.py"]
norecursedirs = ["venv", "old_tests"]
addopts = """
--ds=palpiteiros.settings --no-migrations --reuse-db
--pdbcls=IPython.terminal.debugger:TerminalPdb
--color=yes --quiet --numprocesses=auto
--cov --maxfail=1 --cov-branch
"""

[tool.coverage.run]
branch = true
source = ["."]
omit = [
  "manage.py",
  "venv/*",
  "palpiteiros/*",
  "*/tests/*",
  "*/migrations/*",
  "*/templates/*",
  "*/static/*",
  "*/urls.py",
  "*/constants.py",
  "*/interfaces.py",
]

[tool.coverage.report]
show_missing = true

[tool.ipdb]
context=5
