# Generated by Django 4.1.3 on 2023-05-10 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_source_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("season", models.PositiveIntegerField(verbose_name="Temporada")),
            ],
            options={
                "verbose_name": "competição",
                "verbose_name_plural": "competições",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("nome", models.CharField(max_length=50)),
                ("abreviacao", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                "verbose_name": "equipe",
                "verbose_name_plural": "equipes",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_source_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NS", "Não iniciada"),
                            ("1H", "1º tempo"),
                            ("HT", "Intervalo"),
                            ("2H", "2º tempo"),
                            ("FT", "Encerrada"),
                            ("AET", "Encerrada após prorrogação"),
                            ("PEN", "Encerrada após penalidades"),
                        ],
                        default="NS",
                        max_length=4,
                    ),
                ),
                ("data_hora", models.DateTimeField(verbose_name="Data e hora")),
                ("gols_mandante", models.PositiveIntegerField(blank=True, null=True)),
                ("gols_visitante", models.PositiveIntegerField(blank=True, null=True)),
                ("pontuacao_dobrada", models.BooleanField(default=False)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="core.competition",
                        verbose_name="Competição",
                    ),
                ),
                (
                    "mandante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas_mandante",
                        to="core.equipe",
                    ),
                ),
                (
                    "visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas_visitante",
                        to="core.equipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "partida",
                "verbose_name_plural": "partidas",
                "ordering": ("data_hora",),
                "unique_together": {("mandante", "visitante", "data_hora")},
            },
        ),
        migrations.CreateModel(
            name="Palpiteiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Palpite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gols_mandante", models.PositiveIntegerField()),
                ("gols_visitante", models.PositiveIntegerField()),
                ("pontuacao", models.PositiveIntegerField(default=0)),
                ("contabilizado", models.BooleanField(default=False)),
                (
                    "palpiteiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="palpites",
                        to="core.palpiteiro",
                    ),
                ),
                (
                    "partida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="palpites",
                        to="core.partida",
                    ),
                ),
            ],
            options={
                "verbose_name": "palpite",
                "verbose_name_plural": "palpites",
            },
        ),
        migrations.CreateModel(
            name="GuessPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Atualização"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="identificador público",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nome"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("private", models.BooleanField(default=True, verbose_name="privado")),
                (
                    "new_matches",
                    models.BooleanField(default=False, verbose_name="novas partidas"),
                ),
                (
                    "updated_matches",
                    models.BooleanField(
                        default=False, verbose_name="partidas atualizadas"
                    ),
                ),
                (
                    "competitions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pools",
                        to="core.competition",
                        verbose_name="competições",
                    ),
                ),
                (
                    "guessers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pools",
                        to="core.palpiteiro",
                        verbose_name="palpiteiros",
                    ),
                ),
                (
                    "guesses",
                    models.ManyToManyField(
                        blank=True, related_name="pools", to="core.palpite"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="own_pools",
                        to="core.palpiteiro",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pools",
                        to="core.equipe",
                        verbose_name="times",
                    ),
                ),
            ],
            options={
                "verbose_name": "bolão",
                "verbose_name_plural": "bolões",
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="teams",
            field=models.ManyToManyField(related_name="competitions", to="core.equipe"),
        ),
    ]
