# Generated by Django 4.1.3 on 2024-01-17 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guesser",
            options={
                "verbose_name": "palpiteiro",
                "verbose_name_plural": "palpiteiros",
            },
        ),
    ]
