# Generated by Django 4.1.3 on 2022-11-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palpite",
            name="gols_mandante",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="palpite",
            name="gols_visitante",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="partida",
            name="gols_mandante",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="partida",
            name="gols_visitante",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
