# Generated by Django 4.1.3 on 2023-05-11 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Equipe",
            new_name="Team",
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ("name",),
                "verbose_name": "equipe",
                "verbose_name_plural": "equipes",
            },
        ),
        migrations.RenameField(
            model_name="team",
            old_name="abreviacao",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="nome",
            new_name="name",
        ),
    ]
