# Generated by Django 4.1.3 on 2022-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_palpite_gols_mandante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="abreviacao",
            field=models.CharField(default="???", max_length=3),
        ),
    ]
