# Generated by Django 4.1.3 on 2024-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_guesser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesspool",
            name="hours_before_open_to_guesses",
            field=models.PositiveSmallIntegerField(
                default=48,
                verbose_name="A partir de quantas horas antes do início de uma partida os palpites serão permitidos?",
            ),
        ),
        migrations.AddField(
            model_name="guesspool",
            name="minutes_before_start_match",
            field=models.PositiveSmallIntegerField(
                default=5,
                verbose_name="Até quantos minutos antes do início da partida os palpites serão permitidos?",
            ),
        ),
    ]
