# Generated by Django 4.1.3 on 2024-03-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_guesspool_hours_before_open_to_guesses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guesspool",
            name="competitions",
            field=models.ManyToManyField(
                blank=True,
                related_name="pools",
                to="core.competition",
                verbose_name="Competições",
            ),
        ),
        migrations.AlterField(
            model_name="guesspool",
            name="guessers",
            field=models.ManyToManyField(
                blank=True,
                related_name="pools",
                to="core.guesser",
                verbose_name="Palpiteiros",
            ),
        ),
        migrations.AlterField(
            model_name="guesspool",
            name="guesses",
            field=models.ManyToManyField(
                blank=True,
                related_name="pools",
                to="core.guess",
                verbose_name="Palpites",
            ),
        ),
        migrations.AlterField(
            model_name="guesspool",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="pools", to="core.team", verbose_name="Times"
            ),
        ),
    ]
