# Generated by Django 4.1.3 on 2022-12-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_equipe_abreviacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="palpite",
            name="contabilizado",
            field=models.BooleanField(default=False),
        ),
    ]
