# Generated by Django 4.1.3 on 2023-05-11 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_match_alter_palpite_partida_delete_partida"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Palpiteiro",
            new_name="Guesser",
        ),
        migrations.RenameField(
            model_name="guesser",
            old_name="usuario",
            new_name="user",
        ),
    ]
