# Generated by Django 4.1.3 on 2022-12-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_palpite_contabilizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="palpite",
            name="pontuacao",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
