# Generated by Django 4.1.3 on 2023-05-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_palpiteiro_guesser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_goals", models.PositiveIntegerField()),
                ("away_goals", models.PositiveIntegerField()),
                ("score", models.PositiveIntegerField(default=0)),
                ("consolidated", models.BooleanField(default=False)),
                (
                    "guesser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="core.guesser",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guesses",
                        to="core.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "palpite",
                "verbose_name_plural": "palpites",
            },
        ),
        migrations.DeleteModel(
            name="Palpite",
        ),
        migrations.AlterField(
            model_name="guesspool",
            name="guesses",
            field=models.ManyToManyField(
                blank=True, related_name="pools", to="core.guess"
            ),
        ),
    ]
