# Generated by Django 5.0.6 on 2024-06-28 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_competition_in_progress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={
                "ordering": ("-in_progress", "name"),
                "verbose_name": "competição",
                "verbose_name_plural": "competições",
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Criado em"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competition",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
        ),
        migrations.AlterField(
            model_name="guesspool",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="guesspool",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
        ),
    ]
