# Generated by Django 4.1.3 on 2023-05-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_guess_delete_palpite_alter_guesspool_guesses"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesser",
            name="receive_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Receber notificações"
            ),
        ),
        migrations.AddField(
            model_name="guesser",
            name="supported_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.team",
            ),
        ),
    ]
