# Generated by Django 5.0.6 on 2024-09-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_competition_season"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ("-date_time",), "verbose_name": "partida", "verbose_name_plural": "partidas"},
        ),
        migrations.AddField(
            model_name="competition",
            name="current_season",
            field=models.SmallIntegerField(default=2024, verbose_name="Temporada atual"),
        ),
    ]
