# Generated by Django 4.1.3 on 2023-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_equipe_options_alter_rodada_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partida",
            options={"ordering": ("data_hora",)},
        ),
        migrations.AddField(
            model_name="partida",
            name="pontuacao_dobrada",
            field=models.BooleanField(default=False),
        ),
    ]
