# Generated by Django 5.0.6 on 2025-08-16 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_match_options_competition_current_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="current_season",
            field=models.SmallIntegerField(default=2025, verbose_name="Temporada atual"),
        ),
        migrations.CreateModel(
            name="RankingEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="Modificado em")),
                ("year", models.PositiveSmallIntegerField(verbose_name="Ano")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Mês")),
                ("week", models.PositiveSmallIntegerField(verbose_name="Semana")),
                ("score", models.IntegerField(default=0, verbose_name="Pontuação")),
                (
                    "guesser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ranking_entries", to="core.guesser"
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ranking_entries", to="core.guesspool"
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Classificação",
                "verbose_name_plural": "Registros de Classificação",
                "ordering": ["-score"],
                "unique_together": {("pool", "guesser", "year", "month", "week")},
            },
        ),
    ]
