# Generated by Django 5.0.6 on 2026-03-01 02:35

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_competition_current_season_rankingentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="sfi_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Soccer Football Info ID"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="sfi_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Soccer Football Info ID"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="sfi_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="Soccer Football Info ID"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="current_season",
            field=models.SmallIntegerField(default=core.helpers.get_current_year, verbose_name="Temporada atual"),
        ),
    ]
