# Generated by Django 4.1.3 on 2023-02-01 19:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_partida_options_partida_pontuacao_dobrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rodada",
            name="label",
            field=models.CharField(
                default=core.models.Rodada._generate_label, max_length=50
            ),
        ),
    ]
