# Generated by Django 5.0.6 on 2026-06-03 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_competition_sfi_id_match_sfi_id_team_sfi_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Nome do grupo")),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="groups", to="core.competition"
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True, related_name="competition_groups", to="core.team", verbose_name="Equipes"
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo",
                "verbose_name_plural": "grupos",
                "ordering": ["name"],
                "unique_together": {("competition", "name")},
            },
        ),
    ]
