# Generated by Django 4.1.3 on 2023-02-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_rodada_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rodada",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterField(
            model_name="palpite",
            name="gols_mandante",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="palpite",
            name="gols_visitante",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="palpite",
            name="pontuacao",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
