# Generated by Django 5.0.6 on 2026-06-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_competitiongroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="data_source_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
