# Generated by Django 4.1.3 on 2023-03-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_rodada_options_alter_palpite_gols_mandante_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palpite",
            name="pontuacao",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
