# Generated by Django 5.0.6 on 2026-06-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_competition_data_source_id_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_red_cards",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="away_yellow_cards",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_red_cards",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_yellow_cards",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
