# Generated by Django 4.1.3 on 2023-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_rodada_options_rodada_active_rodada_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="palpite",
            options={"verbose_name": "palpite", "verbose_name_plural": "palpites"},
        ),
        migrations.AlterModelOptions(
            name="partida",
            options={
                "ordering": ("data_hora",),
                "verbose_name": "partida",
                "verbose_name_plural": "partidas",
            },
        ),
        migrations.AlterField(
            model_name="rodada",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="palpite",
            unique_together={("palpiteiro", "partida")},
        ),
        migrations.AlterUniqueTogether(
            name="partida",
            unique_together={("rodada", "mandante", "visitante")},
        ),
    ]
