# Generated by Django 5.0.6 on 2026-06-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_match_cards"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldCupRankingEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="Modificado em")),
                ("start_date", models.DateField(verbose_name="Início do período")),
                ("end_date", models.DateField(verbose_name="Fim do período")),
                ("score", models.IntegerField(default=0, verbose_name="Pontuação")),
                (
                    "guesser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world_cup_ranking_entries",
                        to="core.guesser",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="world_cup_ranking_entries",
                        to="core.guesspool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Classificação Copa",
                "verbose_name_plural": "Registros de Classificação Copa",
                "ordering": ["-score"],
                "unique_together": {("pool", "guesser", "start_date", "end_date")},
            },
        ),
    ]
