# Generated by Django 4.1.3 on 2023-04-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_palpite_options_alter_partida_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rodada",
            options={
                "ordering": ("-id",),
                "verbose_name": "Rodada",
                "verbose_name_plural": "Rodadas",
            },
        ),
    ]
