# Generated by Django 5.0.6 on 2026-06-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_worldcuprankingentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesspool",
            name="hours_to_keep_closed_matches_in_ranking",
            field=models.PositiveSmallIntegerField(
                default=36, verbose_name="Quantas horas manter partidas fechadas no ranking?"
            ),
        ),
    ]
