# Generated by Django 5.0.6 on 2026-06-10 02:21

import django.db.models.deletion
from django.db import migrations, models


def populate_initial_standings(apps, schema_editor):
    from core.models import CompetitionGroup
    for group in CompetitionGroup.objects.all():
        group.recalculate_standings()


def reverse_initial_standings(apps, schema_editor):
    GroupStanding = apps.get_model('core', 'GroupStanding')
    GroupStanding.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_guesspool_hours_to_keep_closed_matches_in_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts', models.PositiveIntegerField(default=0, verbose_name='PTS')),
                ('pj', models.PositiveIntegerField(default=0, verbose_name='PJ')),
                ('gf', models.PositiveIntegerField(default=0, verbose_name='GF')),
                ('ga', models.PositiveIntegerField(default=0, verbose_name='GA')),
                ('gd', models.IntegerField(default=0, verbose_name='GD')),
                ('yc', models.PositiveIntegerField(default=0, verbose_name='YC')),
                ('rc', models.PositiveIntegerField(default=0, verbose_name='RC')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.competitiongroup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_standings', to='core.team')),
            ],
            options={
                'verbose_name': 'classificação de grupo',
                'verbose_name_plural': 'classificações de grupo',
                'ordering': ['-pts', '-gd', '-gf', 'yc', 'rc'],
                'unique_together': {('group', 'team')},
            },
        ),
        migrations.RunPython(
            populate_initial_standings,
            reverse_code=reverse_initial_standings,
        ),
    ]
