# Generated by Django 4.1.3 on 2023-04-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_rodada_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipe",
            options={
                "ordering": ("nome",),
                "verbose_name": "equipe",
                "verbose_name_plural": "equipes",
            },
        ),
        migrations.AlterUniqueTogether(
            name="partida",
            unique_together={("mandante", "visitante", "data_hora")},
        ),
        migrations.CreateModel(
            name="GuessPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Atualização"),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "guessers",
                    models.ManyToManyField(related_name="pools", to="core.palpiteiro"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="own_pools",
                        to="core.palpiteiro",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(related_name="pools", to="core.equipe"),
                ),
            ],
            options={
                "verbose_name": "bolão",
                "verbose_name_plural": "bolões",
            },
        ),
        migrations.AddField(
            model_name="rodada",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="core.guesspool",
            ),
        ),
        migrations.RemoveField(
            model_name="partida",
            name="rodada",
        ),
        migrations.AddField(
            model_name="partida",
            name="rodada",
            field=models.ManyToManyField(related_name="partidas", to="core.rodada"),
        ),
    ]
