# Generated by Django 4.1.3 on 2023-04-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_equipe_options_alter_partida_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rodada",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name="rodada",
            unique_together={("slug", "pool")},
        ),
    ]
