# Generated by Django 4.1.3 on 2023-04-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_rodada_slug_alter_rodada_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rodada",
            name="label",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="rodada",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="core.guesspool",
                verbose_name="Bolão",
            ),
        ),
    ]
