# Generated by Django 4.1.3 on 2023-04-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_guesspool_guessers"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesspool",
            name="guesses",
            field=models.ManyToManyField(
                blank=True, related_name="pools", to="core.palpite"
            ),
        ),
    ]
