# Generated by Django 4.1.3 on 2023-04-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_guesspool_guesses"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="palpite",
            unique_together=set(),
        ),
    ]
