# Generated by Django 4.1.3 on 2023-04-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_palpite_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guesspool",
            name="guessers",
            field=models.ManyToManyField(
                blank=True,
                related_name="pools",
                to="core.palpiteiro",
                verbose_name="palpiteiros",
            ),
        ),
        migrations.AlterField(
            model_name="guesspool",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="nome"),
        ),
        migrations.AlterField(
            model_name="guesspool",
            name="teams",
            field=models.ManyToManyField(
                related_name="pools", to="core.equipe", verbose_name="times"
            ),
        ),
    ]
