# Generated by Django 4.1.3 on 2023-04-18 15:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_guesspool_guessers_alter_guesspool_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesspool",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="identificador público",
            ),
        ),
    ]
