# Generated by Django 4.1.3 on 2023-04-18 15:59

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("core", "guesspool")
    for row in MyModel.objects.all():
        row.uid = uuid.uuid4()
        row.save(update_fields=["uid"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_guesspool_uid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
