# Generated by Django 4.1.3 on 2023-04-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_guesspool_uid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guesspool",
            old_name="uid",
            new_name="uuid",
        ),
    ]
