# Generated by Django 4.1.3 on 2023-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_rename_uid_guesspool_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesspool",
            name="private",
            field=models.BooleanField(default=True, verbose_name="privado"),
        ),
    ]
