# Generated by Django 4.1.3 on 2023-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_guesspool_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesspool",
            name="new_matches",
            field=models.BooleanField(default=False, verbose_name="novas partidas"),
        ),
        migrations.AddField(
            model_name="guesspool",
            name="updated_matches",
            field=models.BooleanField(
                default=False, verbose_name="partidas atualizadas"
            ),
        ),
    ]
