# Generated by Django 4.1.3 on 2023-05-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_guesspool_new_matches_guesspool_updated_matches"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="data_source_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partida",
            name="data_source_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partida",
            name="status",
            field=models.CharField(
                choices=[
                    ("NS", "Não iniciada"),
                    ("LIVE", "Bola rolando"),
                    ("FT", "Encerrada"),
                    ("AET", "Encerrada após prorrogação"),
                    ("PEN", "Encerrada após penalidades"),
                ],
                default="NS",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="partida",
            name="rodada",
            field=models.ManyToManyField(
                blank=True, related_name="partidas", to="core.rodada"
            ),
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_source_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("season", models.PositiveIntegerField(verbose_name="Temporada")),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True, related_name="competitions", to="core.equipe"
                    ),
                ),
            ],
            options={
                "verbose_name": "competição",
                "verbose_name_plural": "competiçõess",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="partida",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="core.competition",
            ),
        ),
    ]
