# Generated by Django 4.1.3 on 2023-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_equipe_abreviacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="abreviacao",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
