# Generated by Django 4.1.3 on 2023-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_equipe_abreviacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partida",
            name="status",
            field=models.CharField(
                choices=[
                    ("NS", "Não iniciada"),
                    ("1H", "1º tempo"),
                    ("HT", "Intervalo"),
                    ("2H", "2º tempo"),
                    ("FT", "Encerrada"),
                    ("AET", "Encerrada após prorrogação"),
                    ("PEN", "Encerrada após penalidades"),
                ],
                default="NS",
                max_length=4,
            ),
        ),
    ]
