# Generated by Django 4.1.3 on 2023-05-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_partida_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={
                "ordering": ("name",),
                "verbose_name": "competição",
                "verbose_name_plural": "competições",
            },
        ),
        migrations.AlterField(
            model_name="competition",
            name="teams",
            field=models.ManyToManyField(related_name="competitions", to="core.equipe"),
        ),
        migrations.AlterField(
            model_name="partida",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="core.competition",
                verbose_name="Competição",
            ),
        ),
    ]
