# Generated by Django 4.1.3 on 2023-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_competition_options_alter_competition_teams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guesspool",
            name="competitions",
            field=models.ManyToManyField(
                blank=True,
                related_name="pools",
                to="core.competition",
                verbose_name="competições",
            ),
        ),
    ]
