# Generated by Django 4.1.3 on 2023-05-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_guesspool_competitions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guesspool",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="pools", to="core.equipe", verbose_name="times"
            ),
        ),
        migrations.AlterField(
            model_name="partida",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="matches",
                to="core.competition",
                verbose_name="Competição",
            ),
        ),
    ]
