version: "3.8"

volumes:
  app_data:
    name: app_data
  app_broker:
    name: app_broker

services:
  django:
    &django
    build: .
    command: ./start.sh server
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 8000:8000

  postgres:
    image: postgres:latest
    volumes:
      - app_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  # redis:
  #   image: redis:6.2.5-alpine
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - app_broker:/var/lib/redis/data

  # celery:
  #   <<: *django
  #   depends_on:
  #     - django
  #     - postgres
  #     - redis
  #   ports:
  #     - 8001:8000
  #   command: ./start.sh worker

  # beat:
  #   <<: *django
  #   depends_on:
  #     - django
  #     - postgres
  #     - redis
  #   ports:
  #     - 8002:8000
  #   command: ./start.sh beat
